// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ARCoreMessage.proto

package com.vayacico.arcoreinbackground;

public final class ARCoreProto {
  private ARCoreProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ArCoreMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:floatingArcore.ArCoreMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .floatingArcore.Position position = 1;</code>
     */
    boolean hasPosition();
    /**
     * <code>required .floatingArcore.Position position = 1;</code>
     */
    Position getPosition();

    /**
     * <code>required .floatingArcore.Rotation rotation = 2;</code>
     */
    boolean hasRotation();
    /**
     * <code>required .floatingArcore.Rotation rotation = 2;</code>
     */
    Rotation getRotation();

    /**
     * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
     */
    boolean hasZaxis();
    /**
     * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
     */
    ZAxis getZaxis();
  }
  /**
   * Protobuf type {@code floatingArcore.ArCoreMessage}
   */
  public  static final class ArCoreMessage extends
      com.google.protobuf.GeneratedMessageLite<
          ArCoreMessage, ArCoreMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:floatingArcore.ArCoreMessage)
      ArCoreMessageOrBuilder {
    private ArCoreMessage() {
    }
    private int bitField0_;
    public static final int POSITION_FIELD_NUMBER = 1;
    private Position position_;
    /**
     * <code>required .floatingArcore.Position position = 1;</code>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .floatingArcore.Position position = 1;</code>
     */
    public Position getPosition() {
      return position_ == null ? Position.getDefaultInstance() : position_;
    }
    /**
     * <code>required .floatingArcore.Position position = 1;</code>
     */
    private void setPosition(Position value) {
      if (value == null) {
        throw new NullPointerException();
      }
      position_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>required .floatingArcore.Position position = 1;</code>
     */
    private void setPosition(
        Position.Builder builderForValue) {
      position_ = builderForValue.build();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>required .floatingArcore.Position position = 1;</code>
     */
    private void mergePosition(Position value) {
      if (position_ != null &&
          position_ != Position.getDefaultInstance()) {
        position_ =
          Position.newBuilder(position_).mergeFrom(value).buildPartial();
      } else {
        position_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>required .floatingArcore.Position position = 1;</code>
     */
    private void clearPosition() {  position_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int ROTATION_FIELD_NUMBER = 2;
    private Rotation rotation_;
    /**
     * <code>required .floatingArcore.Rotation rotation = 2;</code>
     */
    public boolean hasRotation() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .floatingArcore.Rotation rotation = 2;</code>
     */
    public Rotation getRotation() {
      return rotation_ == null ? Rotation.getDefaultInstance() : rotation_;
    }
    /**
     * <code>required .floatingArcore.Rotation rotation = 2;</code>
     */
    private void setRotation(Rotation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      rotation_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <code>required .floatingArcore.Rotation rotation = 2;</code>
     */
    private void setRotation(
        Rotation.Builder builderForValue) {
      rotation_ = builderForValue.build();
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>required .floatingArcore.Rotation rotation = 2;</code>
     */
    private void mergeRotation(Rotation value) {
      if (rotation_ != null &&
          rotation_ != Rotation.getDefaultInstance()) {
        rotation_ =
          Rotation.newBuilder(rotation_).mergeFrom(value).buildPartial();
      } else {
        rotation_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>required .floatingArcore.Rotation rotation = 2;</code>
     */
    private void clearRotation() {  rotation_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static final int ZAXIS_FIELD_NUMBER = 3;
    private ZAxis zaxis_;
    /**
     * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
     */
    public boolean hasZaxis() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
     */
    public ZAxis getZaxis() {
      return zaxis_ == null ? ZAxis.getDefaultInstance() : zaxis_;
    }
    /**
     * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
     */
    private void setZaxis(ZAxis value) {
      if (value == null) {
        throw new NullPointerException();
      }
      zaxis_ = value;
      bitField0_ |= 0x00000004;
      }
    /**
     * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
     */
    private void setZaxis(
        ZAxis.Builder builderForValue) {
      zaxis_ = builderForValue.build();
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
     */
    private void mergeZaxis(ZAxis value) {
      if (zaxis_ != null &&
          zaxis_ != ZAxis.getDefaultInstance()) {
        zaxis_ =
          ZAxis.newBuilder(zaxis_).mergeFrom(value).buildPartial();
      } else {
        zaxis_ = value;
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
     */
    private void clearZaxis() {  zaxis_ = null;
      bitField0_ = (bitField0_ & ~0x00000004);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getPosition());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getRotation());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getZaxis());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPosition());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRotation());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getZaxis());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static ArCoreMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ArCoreMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ArCoreMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ArCoreMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ArCoreMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ArCoreMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ArCoreMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ArCoreMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ArCoreMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ArCoreMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ArCoreMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code floatingArcore.ArCoreMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ArCoreMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:floatingArcore.ArCoreMessage)
        ArCoreMessageOrBuilder {
      // Construct using com.vayacico.floatingarcore.ARCoreProto.ArCoreMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .floatingArcore.Position position = 1;</code>
       */
      public boolean hasPosition() {
        return instance.hasPosition();
      }
      /**
       * <code>required .floatingArcore.Position position = 1;</code>
       */
      public Position getPosition() {
        return instance.getPosition();
      }
      /**
       * <code>required .floatingArcore.Position position = 1;</code>
       */
      public Builder setPosition(Position value) {
        copyOnWrite();
        instance.setPosition(value);
        return this;
        }
      /**
       * <code>required .floatingArcore.Position position = 1;</code>
       */
      public Builder setPosition(
          Position.Builder builderForValue) {
        copyOnWrite();
        instance.setPosition(builderForValue);
        return this;
      }
      /**
       * <code>required .floatingArcore.Position position = 1;</code>
       */
      public Builder mergePosition(Position value) {
        copyOnWrite();
        instance.mergePosition(value);
        return this;
      }
      /**
       * <code>required .floatingArcore.Position position = 1;</code>
       */
      public Builder clearPosition() {  copyOnWrite();
        instance.clearPosition();
        return this;
      }

      /**
       * <code>required .floatingArcore.Rotation rotation = 2;</code>
       */
      public boolean hasRotation() {
        return instance.hasRotation();
      }
      /**
       * <code>required .floatingArcore.Rotation rotation = 2;</code>
       */
      public Rotation getRotation() {
        return instance.getRotation();
      }
      /**
       * <code>required .floatingArcore.Rotation rotation = 2;</code>
       */
      public Builder setRotation(Rotation value) {
        copyOnWrite();
        instance.setRotation(value);
        return this;
        }
      /**
       * <code>required .floatingArcore.Rotation rotation = 2;</code>
       */
      public Builder setRotation(
          Rotation.Builder builderForValue) {
        copyOnWrite();
        instance.setRotation(builderForValue);
        return this;
      }
      /**
       * <code>required .floatingArcore.Rotation rotation = 2;</code>
       */
      public Builder mergeRotation(Rotation value) {
        copyOnWrite();
        instance.mergeRotation(value);
        return this;
      }
      /**
       * <code>required .floatingArcore.Rotation rotation = 2;</code>
       */
      public Builder clearRotation() {  copyOnWrite();
        instance.clearRotation();
        return this;
      }

      /**
       * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
       */
      public boolean hasZaxis() {
        return instance.hasZaxis();
      }
      /**
       * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
       */
      public ZAxis getZaxis() {
        return instance.getZaxis();
      }
      /**
       * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
       */
      public Builder setZaxis(ZAxis value) {
        copyOnWrite();
        instance.setZaxis(value);
        return this;
        }
      /**
       * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
       */
      public Builder setZaxis(
          ZAxis.Builder builderForValue) {
        copyOnWrite();
        instance.setZaxis(builderForValue);
        return this;
      }
      /**
       * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
       */
      public Builder mergeZaxis(ZAxis value) {
        copyOnWrite();
        instance.mergeZaxis(value);
        return this;
      }
      /**
       * <code>required .floatingArcore.ZAxis zaxis = 3;</code>
       */
      public Builder clearZaxis() {  copyOnWrite();
        instance.clearZaxis();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:floatingArcore.ArCoreMessage)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ArCoreMessage();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasPosition()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasRotation()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasZaxis()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!getPosition().isInitialized()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!getRotation().isInitialized()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!getZaxis().isInitialized()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ArCoreMessage other = (ArCoreMessage) arg1;
          position_ = visitor.visitMessage(position_, other.position_);
          rotation_ = visitor.visitMessage(rotation_, other.rotation_);
          zaxis_ = visitor.visitMessage(zaxis_, other.zaxis_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  Position.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    subBuilder = position_.toBuilder();
                  }
                  position_ = input.readMessage(Position.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(position_);
                    position_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000001;
                  break;
                }
                case 18: {
                  Rotation.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    subBuilder = rotation_.toBuilder();
                  }
                  rotation_ = input.readMessage(Rotation.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(rotation_);
                    rotation_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000002;
                  break;
                }
                case 26: {
                  ZAxis.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    subBuilder = zaxis_.toBuilder();
                  }
                  zaxis_ = input.readMessage(ZAxis.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(zaxis_);
                    zaxis_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000004;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ArCoreMessage.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:floatingArcore.ArCoreMessage)
    private static final ArCoreMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ArCoreMessage();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ArCoreMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ArCoreMessage> PARSER;

    public static com.google.protobuf.Parser<ArCoreMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:floatingArcore.Position)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required double tx = 1;</code>
     */
    boolean hasTx();
    /**
     * <code>required double tx = 1;</code>
     */
    double getTx();

    /**
     * <code>required double ty = 2;</code>
     */
    boolean hasTy();
    /**
     * <code>required double ty = 2;</code>
     */
    double getTy();

    /**
     * <code>required double tz = 3;</code>
     */
    boolean hasTz();
    /**
     * <code>required double tz = 3;</code>
     */
    double getTz();
  }
  /**
   * Protobuf type {@code floatingArcore.Position}
   */
  public  static final class Position extends
      com.google.protobuf.GeneratedMessageLite<
          Position, Position.Builder> implements
      // @@protoc_insertion_point(message_implements:floatingArcore.Position)
      PositionOrBuilder {
    private Position() {
    }
    private int bitField0_;
    public static final int TX_FIELD_NUMBER = 1;
    private double tx_;
    /**
     * <code>required double tx = 1;</code>
     */
    public boolean hasTx() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double tx = 1;</code>
     */
    public double getTx() {
      return tx_;
    }
    /**
     * <code>required double tx = 1;</code>
     */
    private void setTx(double value) {
      bitField0_ |= 0x00000001;
      tx_ = value;
    }
    /**
     * <code>required double tx = 1;</code>
     */
    private void clearTx() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tx_ = 0D;
    }

    public static final int TY_FIELD_NUMBER = 2;
    private double ty_;
    /**
     * <code>required double ty = 2;</code>
     */
    public boolean hasTy() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double ty = 2;</code>
     */
    public double getTy() {
      return ty_;
    }
    /**
     * <code>required double ty = 2;</code>
     */
    private void setTy(double value) {
      bitField0_ |= 0x00000002;
      ty_ = value;
    }
    /**
     * <code>required double ty = 2;</code>
     */
    private void clearTy() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ty_ = 0D;
    }

    public static final int TZ_FIELD_NUMBER = 3;
    private double tz_;
    /**
     * <code>required double tz = 3;</code>
     */
    public boolean hasTz() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double tz = 3;</code>
     */
    public double getTz() {
      return tz_;
    }
    /**
     * <code>required double tz = 3;</code>
     */
    private void setTz(double value) {
      bitField0_ |= 0x00000004;
      tz_ = value;
    }
    /**
     * <code>required double tz = 3;</code>
     */
    private void clearTz() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tz_ = 0D;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, tx_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, ty_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, tz_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, tx_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, ty_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, tz_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Position prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code floatingArcore.Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Position, Builder> implements
        // @@protoc_insertion_point(builder_implements:floatingArcore.Position)
        PositionOrBuilder {
      // Construct using com.vayacico.floatingarcore.ARCoreProto.Position.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required double tx = 1;</code>
       */
      public boolean hasTx() {
        return instance.hasTx();
      }
      /**
       * <code>required double tx = 1;</code>
       */
      public double getTx() {
        return instance.getTx();
      }
      /**
       * <code>required double tx = 1;</code>
       */
      public Builder setTx(double value) {
        copyOnWrite();
        instance.setTx(value);
        return this;
      }
      /**
       * <code>required double tx = 1;</code>
       */
      public Builder clearTx() {
        copyOnWrite();
        instance.clearTx();
        return this;
      }

      /**
       * <code>required double ty = 2;</code>
       */
      public boolean hasTy() {
        return instance.hasTy();
      }
      /**
       * <code>required double ty = 2;</code>
       */
      public double getTy() {
        return instance.getTy();
      }
      /**
       * <code>required double ty = 2;</code>
       */
      public Builder setTy(double value) {
        copyOnWrite();
        instance.setTy(value);
        return this;
      }
      /**
       * <code>required double ty = 2;</code>
       */
      public Builder clearTy() {
        copyOnWrite();
        instance.clearTy();
        return this;
      }

      /**
       * <code>required double tz = 3;</code>
       */
      public boolean hasTz() {
        return instance.hasTz();
      }
      /**
       * <code>required double tz = 3;</code>
       */
      public double getTz() {
        return instance.getTz();
      }
      /**
       * <code>required double tz = 3;</code>
       */
      public Builder setTz(double value) {
        copyOnWrite();
        instance.setTz(value);
        return this;
      }
      /**
       * <code>required double tz = 3;</code>
       */
      public Builder clearTz() {
        copyOnWrite();
        instance.clearTz();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:floatingArcore.Position)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Position();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasTx()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasTy()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasTz()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Position other = (Position) arg1;
          tx_ = visitor.visitDouble(
              hasTx(), tx_,
              other.hasTx(), other.tx_);
          ty_ = visitor.visitDouble(
              hasTy(), ty_,
              other.hasTy(), other.ty_);
          tz_ = visitor.visitDouble(
              hasTz(), tz_,
              other.hasTz(), other.tz_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 9: {
                  bitField0_ |= 0x00000001;
                  tx_ = input.readDouble();
                  break;
                }
                case 17: {
                  bitField0_ |= 0x00000002;
                  ty_ = input.readDouble();
                  break;
                }
                case 25: {
                  bitField0_ |= 0x00000004;
                  tz_ = input.readDouble();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Position.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:floatingArcore.Position)
    private static final Position DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Position();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Position getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Position> PARSER;

    public static com.google.protobuf.Parser<Position> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RotationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:floatingArcore.Rotation)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required double qw = 1;</code>
     */
    boolean hasQw();
    /**
     * <code>required double qw = 1;</code>
     */
    double getQw();

    /**
     * <code>required double qx = 2;</code>
     */
    boolean hasQx();
    /**
     * <code>required double qx = 2;</code>
     */
    double getQx();

    /**
     * <code>required double qy = 3;</code>
     */
    boolean hasQy();
    /**
     * <code>required double qy = 3;</code>
     */
    double getQy();

    /**
     * <code>required double qz = 4;</code>
     */
    boolean hasQz();
    /**
     * <code>required double qz = 4;</code>
     */
    double getQz();
  }
  /**
   * Protobuf type {@code floatingArcore.Rotation}
   */
  public  static final class Rotation extends
      com.google.protobuf.GeneratedMessageLite<
          Rotation, Rotation.Builder> implements
      // @@protoc_insertion_point(message_implements:floatingArcore.Rotation)
      RotationOrBuilder {
    private Rotation() {
    }
    private int bitField0_;
    public static final int QW_FIELD_NUMBER = 1;
    private double qw_;
    /**
     * <code>required double qw = 1;</code>
     */
    public boolean hasQw() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double qw = 1;</code>
     */
    public double getQw() {
      return qw_;
    }
    /**
     * <code>required double qw = 1;</code>
     */
    private void setQw(double value) {
      bitField0_ |= 0x00000001;
      qw_ = value;
    }
    /**
     * <code>required double qw = 1;</code>
     */
    private void clearQw() {
      bitField0_ = (bitField0_ & ~0x00000001);
      qw_ = 0D;
    }

    public static final int QX_FIELD_NUMBER = 2;
    private double qx_;
    /**
     * <code>required double qx = 2;</code>
     */
    public boolean hasQx() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double qx = 2;</code>
     */
    public double getQx() {
      return qx_;
    }
    /**
     * <code>required double qx = 2;</code>
     */
    private void setQx(double value) {
      bitField0_ |= 0x00000002;
      qx_ = value;
    }
    /**
     * <code>required double qx = 2;</code>
     */
    private void clearQx() {
      bitField0_ = (bitField0_ & ~0x00000002);
      qx_ = 0D;
    }

    public static final int QY_FIELD_NUMBER = 3;
    private double qy_;
    /**
     * <code>required double qy = 3;</code>
     */
    public boolean hasQy() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double qy = 3;</code>
     */
    public double getQy() {
      return qy_;
    }
    /**
     * <code>required double qy = 3;</code>
     */
    private void setQy(double value) {
      bitField0_ |= 0x00000004;
      qy_ = value;
    }
    /**
     * <code>required double qy = 3;</code>
     */
    private void clearQy() {
      bitField0_ = (bitField0_ & ~0x00000004);
      qy_ = 0D;
    }

    public static final int QZ_FIELD_NUMBER = 4;
    private double qz_;
    /**
     * <code>required double qz = 4;</code>
     */
    public boolean hasQz() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double qz = 4;</code>
     */
    public double getQz() {
      return qz_;
    }
    /**
     * <code>required double qz = 4;</code>
     */
    private void setQz(double value) {
      bitField0_ |= 0x00000008;
      qz_ = value;
    }
    /**
     * <code>required double qz = 4;</code>
     */
    private void clearQz() {
      bitField0_ = (bitField0_ & ~0x00000008);
      qz_ = 0D;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, qw_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, qx_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, qy_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, qz_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, qw_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, qx_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, qy_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, qz_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static Rotation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Rotation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Rotation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Rotation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Rotation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Rotation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Rotation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Rotation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Rotation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Rotation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Rotation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code floatingArcore.Rotation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Rotation, Builder> implements
        // @@protoc_insertion_point(builder_implements:floatingArcore.Rotation)
        RotationOrBuilder {
      // Construct using com.vayacico.floatingarcore.ARCoreProto.Rotation.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required double qw = 1;</code>
       */
      public boolean hasQw() {
        return instance.hasQw();
      }
      /**
       * <code>required double qw = 1;</code>
       */
      public double getQw() {
        return instance.getQw();
      }
      /**
       * <code>required double qw = 1;</code>
       */
      public Builder setQw(double value) {
        copyOnWrite();
        instance.setQw(value);
        return this;
      }
      /**
       * <code>required double qw = 1;</code>
       */
      public Builder clearQw() {
        copyOnWrite();
        instance.clearQw();
        return this;
      }

      /**
       * <code>required double qx = 2;</code>
       */
      public boolean hasQx() {
        return instance.hasQx();
      }
      /**
       * <code>required double qx = 2;</code>
       */
      public double getQx() {
        return instance.getQx();
      }
      /**
       * <code>required double qx = 2;</code>
       */
      public Builder setQx(double value) {
        copyOnWrite();
        instance.setQx(value);
        return this;
      }
      /**
       * <code>required double qx = 2;</code>
       */
      public Builder clearQx() {
        copyOnWrite();
        instance.clearQx();
        return this;
      }

      /**
       * <code>required double qy = 3;</code>
       */
      public boolean hasQy() {
        return instance.hasQy();
      }
      /**
       * <code>required double qy = 3;</code>
       */
      public double getQy() {
        return instance.getQy();
      }
      /**
       * <code>required double qy = 3;</code>
       */
      public Builder setQy(double value) {
        copyOnWrite();
        instance.setQy(value);
        return this;
      }
      /**
       * <code>required double qy = 3;</code>
       */
      public Builder clearQy() {
        copyOnWrite();
        instance.clearQy();
        return this;
      }

      /**
       * <code>required double qz = 4;</code>
       */
      public boolean hasQz() {
        return instance.hasQz();
      }
      /**
       * <code>required double qz = 4;</code>
       */
      public double getQz() {
        return instance.getQz();
      }
      /**
       * <code>required double qz = 4;</code>
       */
      public Builder setQz(double value) {
        copyOnWrite();
        instance.setQz(value);
        return this;
      }
      /**
       * <code>required double qz = 4;</code>
       */
      public Builder clearQz() {
        copyOnWrite();
        instance.clearQz();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:floatingArcore.Rotation)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Rotation();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasQw()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasQx()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasQy()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasQz()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Rotation other = (Rotation) arg1;
          qw_ = visitor.visitDouble(
              hasQw(), qw_,
              other.hasQw(), other.qw_);
          qx_ = visitor.visitDouble(
              hasQx(), qx_,
              other.hasQx(), other.qx_);
          qy_ = visitor.visitDouble(
              hasQy(), qy_,
              other.hasQy(), other.qy_);
          qz_ = visitor.visitDouble(
              hasQz(), qz_,
              other.hasQz(), other.qz_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 9: {
                  bitField0_ |= 0x00000001;
                  qw_ = input.readDouble();
                  break;
                }
                case 17: {
                  bitField0_ |= 0x00000002;
                  qx_ = input.readDouble();
                  break;
                }
                case 25: {
                  bitField0_ |= 0x00000004;
                  qy_ = input.readDouble();
                  break;
                }
                case 33: {
                  bitField0_ |= 0x00000008;
                  qz_ = input.readDouble();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Rotation.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:floatingArcore.Rotation)
    private static final Rotation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Rotation();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Rotation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Rotation> PARSER;

    public static com.google.protobuf.Parser<Rotation> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ZAxisOrBuilder extends
      // @@protoc_insertion_point(interface_extends:floatingArcore.ZAxis)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required double x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required double x = 1;</code>
     */
    double getX();

    /**
     * <code>required double y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required double y = 2;</code>
     */
    double getY();

    /**
     * <code>required double z = 3;</code>
     */
    boolean hasZ();
    /**
     * <code>required double z = 3;</code>
     */
    double getZ();
  }
  /**
   * Protobuf type {@code floatingArcore.ZAxis}
   */
  public  static final class ZAxis extends
      com.google.protobuf.GeneratedMessageLite<
          ZAxis, ZAxis.Builder> implements
      // @@protoc_insertion_point(message_implements:floatingArcore.ZAxis)
      ZAxisOrBuilder {
    private ZAxis() {
    }
    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    /**
     * <code>required double x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double x = 1;</code>
     */
    public double getX() {
      return x_;
    }
    /**
     * <code>required double x = 1;</code>
     */
    private void setX(double value) {
      bitField0_ |= 0x00000001;
      x_ = value;
    }
    /**
     * <code>required double x = 1;</code>
     */
    private void clearX() {
      bitField0_ = (bitField0_ & ~0x00000001);
      x_ = 0D;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    /**
     * <code>required double y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double y = 2;</code>
     */
    public double getY() {
      return y_;
    }
    /**
     * <code>required double y = 2;</code>
     */
    private void setY(double value) {
      bitField0_ |= 0x00000002;
      y_ = value;
    }
    /**
     * <code>required double y = 2;</code>
     */
    private void clearY() {
      bitField0_ = (bitField0_ & ~0x00000002);
      y_ = 0D;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private double z_;
    /**
     * <code>required double z = 3;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double z = 3;</code>
     */
    public double getZ() {
      return z_;
    }
    /**
     * <code>required double z = 3;</code>
     */
    private void setZ(double value) {
      bitField0_ |= 0x00000004;
      z_ = value;
    }
    /**
     * <code>required double z = 3;</code>
     */
    private void clearZ() {
      bitField0_ = (bitField0_ & ~0x00000004);
      z_ = 0D;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, z_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, z_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static ZAxis parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ZAxis parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ZAxis parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ZAxis parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ZAxis parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ZAxis parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ZAxis parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ZAxis parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ZAxis parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ZAxis parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ZAxis prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code floatingArcore.ZAxis}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ZAxis, Builder> implements
        // @@protoc_insertion_point(builder_implements:floatingArcore.ZAxis)
        ZAxisOrBuilder {
      // Construct using com.vayacico.floatingarcore.ARCoreProto.ZAxis.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required double x = 1;</code>
       */
      public boolean hasX() {
        return instance.hasX();
      }
      /**
       * <code>required double x = 1;</code>
       */
      public double getX() {
        return instance.getX();
      }
      /**
       * <code>required double x = 1;</code>
       */
      public Builder setX(double value) {
        copyOnWrite();
        instance.setX(value);
        return this;
      }
      /**
       * <code>required double x = 1;</code>
       */
      public Builder clearX() {
        copyOnWrite();
        instance.clearX();
        return this;
      }

      /**
       * <code>required double y = 2;</code>
       */
      public boolean hasY() {
        return instance.hasY();
      }
      /**
       * <code>required double y = 2;</code>
       */
      public double getY() {
        return instance.getY();
      }
      /**
       * <code>required double y = 2;</code>
       */
      public Builder setY(double value) {
        copyOnWrite();
        instance.setY(value);
        return this;
      }
      /**
       * <code>required double y = 2;</code>
       */
      public Builder clearY() {
        copyOnWrite();
        instance.clearY();
        return this;
      }

      /**
       * <code>required double z = 3;</code>
       */
      public boolean hasZ() {
        return instance.hasZ();
      }
      /**
       * <code>required double z = 3;</code>
       */
      public double getZ() {
        return instance.getZ();
      }
      /**
       * <code>required double z = 3;</code>
       */
      public Builder setZ(double value) {
        copyOnWrite();
        instance.setZ(value);
        return this;
      }
      /**
       * <code>required double z = 3;</code>
       */
      public Builder clearZ() {
        copyOnWrite();
        instance.clearZ();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:floatingArcore.ZAxis)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ZAxis();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasX()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasY()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasZ()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          ZAxis other = (ZAxis) arg1;
          x_ = visitor.visitDouble(
              hasX(), x_,
              other.hasX(), other.x_);
          y_ = visitor.visitDouble(
              hasY(), y_,
              other.hasY(), other.y_);
          z_ = visitor.visitDouble(
              hasZ(), z_,
              other.hasZ(), other.z_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 9: {
                  bitField0_ |= 0x00000001;
                  x_ = input.readDouble();
                  break;
                }
                case 17: {
                  bitField0_ |= 0x00000002;
                  y_ = input.readDouble();
                  break;
                }
                case 25: {
                  bitField0_ |= 0x00000004;
                  z_ = input.readDouble();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (ZAxis.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:floatingArcore.ZAxis)
    private static final ZAxis DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ZAxis();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static ZAxis getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ZAxis> PARSER;

    public static com.google.protobuf.Parser<ZAxis> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
